### ISSUE TITLE
Arbitrary user can cancel nft sale in nft-fixprice-sale.fc

### ISSUE THREAD

**Issue by donjaron777** [getgems-io/nft-contracts#3]
Missing the check  in L139:

_throw_unless(458, equal_slices(sender_address, nft_owner_address) | equal_slices(sender_address, marketplace_address));_

anybody can cancel sale  in nft-fixprice-sale.fc

**Comment by stels-cs** [comment]
Yes, it is, but we do not use this version of the contract. 
nft-fixprice-sale-v2 used now

**Comment by MMYYSS** [comment]
😃
