### ISSUE TITLE
Clim nft dogs

### ISSUE THREAD

**Issue by Mohammadbaluchgharayi** [getgems-io/nft-contracts#60]
Thanks for helping us!

**Describe the bug**
Please describe what went wrong and how we can fix that.

**Expected behavior**

**Additional context**

**Comment by Mohammadbaluchgharayi** [comment]
Clime nft dags

**Comment by homira135** [comment]
- [ ] سلام وعرض ادب .دوردبابت تیم خوب وفعالان دراین زمینه چون واقعاپشتیبانی خوب خوبی دارن ارائه میدن به کاربران .درمحیط ومنطقه من محدویت اینترانت وقطع وصل شدن بسیاراست وچداازاون واقعاتچربه ودانش دراین زمینه روندارم
