### ISSUE TITLE
UQBKK06RquMT0WifLgjIwM54VyPpXVoUHRSH2bSiBF8P1SyV

### ISSUE THREAD

**Issue by Alireza703** [getgems-io/nft-contracts#61]
**Summary**
Please describe your idea in one paragraph.

**Motivation**
Why do you think this problem is important? 

**Describe the solution you'd like**
Please explain how you propose to solve this issue

**Comment by Alireza703** [comment]
UQBKK06RquMT0WifLgjIwM54VyPpXVoUHRSH2bSiBF8P1SyV

**Comment by Hassan222-ux** [comment]
https://github.com/getgems-io/nft-contracts/issues/61](url)

**Comment by Hassan222-ux** [comment]
[ConnectedAppsList.tsx.txt](https://github.com/user-attachments/files/19558183/ConnectedAppsList.tsx.txt)

**Comment by kulih-kyber** [comment]
Duplicate of #19
