### ISSUE TITLE
Good

### ISSUE THREAD

**Issue by Madesupra27** [getgems-io/nft-contracts#71]
https://www.binance.info/activity/referral-entry/CPA/together-v4?hl=id&ref=CPA_00E9N2U0V6![share_2024-10-24_12_20_00_602.jpeg_2024-10-24_12_20_00.jpg](https://github.com/user-attachments/assets/344af5dd-f044-4f08-a0d5-ab4c7c51665b)

**Comment by hossen71** [comment]
goodn
